enum ErrorEnum {
    NETWORK_ERROR = 'NETWORK_ERROR',
    UNKOWN_ERROR = 'UNKOWN_ERROR',
    BAD_REQUEST = 'BAD_REQUEST',
    FORBIDDEN = 'FORBIDDEN',
    NOT_FOUND = 'NOT_FOUND',
    SERVER_ERROR = 'SERVER_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    TIMEOUT_ERROR = 'TIMEOUT_ERROR',
    FETCH_ERROR = 'FETCH_ERROR',
}

export  {ErrorEnum}